# Site settings
title: Paul M. Carrier
tagline: Software, projects, and notes
email: paulmcarrier@gmail.com
description: >-
  Software Engineer at the Walt Disney Company.
baseurl: ""
url: "https://paulmcarrier.com"
lang: en

author:
  name: Paul M. Carrier
  url: https://github.com/paulmcarrier

# Build settings
remote_theme: paulmcarrier/monophase@main
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
