# Site settings
title: Paul M. Carrier
tagline: Dad. Software Engineer @ Disney.
email: paulmcarrier@gmail.com
description: >-
  Dad. Software Engineer @ Disney.
baseurl: ""
url: "https://paulmcarrier.com"
lang: en

author:
  name: Paul M. Carrier
  url: https://github.com/paulmcarrier

# Build settings
remote_theme: paulmcarrier/monophase@main
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
